<?php
$pre = 'skip_fbapi';
include_once 'include/config.php';
include_once 'include/functions.php';
?>

<?php 
// Due to the database transition, this converts all types into one ID for older versions of the player.
if(!isset($_GET['id'])) {
	if(isset($_GET['link']))
		$id = $_GET['link'];
	elseif (isset($_GET['upload']))
		$id = $_GET['upload'];
	elseif (isset($_GET['from_feed']))
		$id = $_GET['from_feed'];
}
?>

<?php
$db_data = $db->Raw("SELECT `xid`,`user`,`type`,`link`,`title`,`artist`,`playtime` FROM `userdb_uploads` WHERE `xid`='$id' OR `id`='$id';");
$id = $db_data[0]['xid'];
$type = $db_data[0]['type'];
	
if (is_null($db_data[0])) {
	error('Data could not be located!','Check the input ID or URL and try again. If the problem still persists, please contact the developer.');
	die();
}

$title = htmlspecialchars(utf8_encode($db_data[0]['title']), ENT_QUOTES);
$artist = htmlspecialchars(utf8_encode($db_data[0]['artist']), ENT_QUOTES);

if($type == 'link') {
	$link = $db_data[0]['link'];
	$duration = 0;
	$urlParse = parse_url($link);
	if ($urlParse['host'] == 'youtube.com')
		$provider = 'youtube';
	else
		$provider = 'sound';
} elseif ($type == 'upload') {
	$uploadData = $db->Raw("SELECT `user`,`server`,`drive` FROM `userdb_uploads` WHERE `id`='$id' OR `xid`='$id';");
	$server = $uploadData[0]['server'];
	$serverData = $db->Raw("SELECT `stream_url`,`stream_secret` FROM `servers` WHERE `name`='$server'");
	
	$userFolder = array_sum(str_split($uploadData[0]['user']));
	
	$f = "/" . $uploadData[0]['drive'] . "/" . $userFolder . "/" . basename($db_data[0]['link']) . "";

	$t_hex = sprintf("%08x", time());
	$m = md5($serverData[0]['stream_secret'].$f.$t_hex);

	$link = "" . $serverData[0]['stream_url'] . "/stream/" . $m . "/" . $t_hex . "" . $f . "";
	
	if($db_data[0]['playtime'] == '') $duration = 0; else $duration = $db_data[0]['playtime'];
	$provider = 'sound';
}

?>

<?php if(isset($_GET['from_share']) || isset($_GET['from_embed'])) { ?>
	<?php if ($challenge !== $db_data[0]['user']) { ?>
		<div style="font-size: 2em"><b>404 - Not Found</b></div>
		<?php die(); ?>
	<?php } ?>
	
	<?php if(isset($_GET['from_share'])) { ?><center><b>"<?php echo htmlspecialchars_decode(utf8_decode($db_data[0]['title']), ENT_QUOTES); ?>" by <?php echo htmlspecialchars_decode(utf8_decode($db_data[0]['artist']), ENT_QUOTES); ?></b></center><?php } ?>
	<center>
	<embed
		src="<?php echo $config['fb']['appcallbackurl']; ?>flash/player/player.swf" 
		flashvars="file=<?php echo $link; ?>&autostart=<?php echo $_GET['autostart']; ?>&fullscreen=false&skin=<?php echo $config['fb']['appcallbackurl']; ?>flash/skin/stylish.swf&backcolor=#3b5998&lightcolor=#ffffff&frontcolor=#f7f7f7&abouttext=0&aboutlink=0&volume=75&duration=<?php echo $duration; ?>&bufferlength=1&provider=<?php echo $provider; ?>"
		height="30"
		width="<?php if(isset($_GET['from_share'])) echo '600'; else echo '300'; ?>"
	/>
	</center>
	<?php if(isset($_GET['from_share'])) { ?><br /><center>Page generated by the <a href="<?php echo $config['fb']['fburl'] ?>">Music Application</a></center><?php } ?>
<?php } ?>

<?php if(isset($_GET['from_edit']) || isset($_GET['from_friends']) || isset($_GET['from_tab']) || isset($_GET['from_explore'])) { ?>
	<fb:swf 
		swfsrc="<?php echo $config['fb']['appcallbackurl']; ?>flash/player/player.swf" 
		flashvars="file=<?php echo $link; ?>&autostart=true&fullscreen=false&skin=<?php echo $config['fb']['appcallbackurl']; ?>flash/skin/stylish.swf&backcolor=#3b5998&lightcolor=#ffffff&frontcolor=#f7f7f7&abouttext=0&aboutlink=0&volume=75&duration=<?php echo $duration; ?>&bufferlength=1&provider=<?php echo $provider; ?>"
		quality="high" 
		height="30" 
		width="<?php if(isset($from_edit)) echo "530"; elseif(isset($from_friends)) echo "420"; elseif(isset($from_tab)) echo "760"; elseif(isset($from_explore)) echo "400"; ?>" 
	/>
<?php } elseif(isset($_GET['from_feed'])) { ?>
	<playlist version="1" xmlns="http://xspf.org/ns/0/">
		<tracklist>
	
			<track>
				<location><?php echo $link; ?></location>
			</track>
	
		</tracklist>
	</playlist>
<?php } else { ?>
	<fb:wide>
		<fb:swf 
			swfsrc="<?php echo $config['fb']['appcallbackurl']; ?>flash/player/player.swf" 
			flashvars="file=<?php echo $link; ?>&autostart=true&fullscreen=false&skin=<?php echo $config['fb']['appcallbackurl']; ?>flash/skin/stylish.swf&backcolor=#3b5998&lightcolor=#ffffff&frontcolor=#f7f7f7&abouttext=0&aboutlink=0&volume=75&duration=<?php echo $duration; ?>&bufferlength=1&provider=<?php echo $provider; ?>"
			quality="high" 
			height="30" 
			width="380" 
		/>
	</fb:wide>
	<fb:narrow>
		<fb:swf 
			swfsrc="<?php echo $config['fb']['appcallbackurl']; ?>flash/player/player.swf" 
			flashvars="file=<?php echo $link; ?>&autostart=true&fullscreen=false&skin=<?php echo $config['fb']['appcallbackurl']; ?>flash/skin/stylish_small.swf&backcolor=#3b5998&lightcolor=#ffffff&frontcolor=#f7f7f7&abouttext=0&aboutlink=0&volume=75&duration=<?php echo $duration; ?>&bufferlength=1&provider=<?php echo $provider; ?>" 
			quality="high"
			height="30" 
			width="184" 
			/>
	</fb:narrow>
<?php } ?>

<?php
if (!isset($_GET['from_feed'])) {
	$owner = $db_data[0]['user'];
	$player = $_POST['fb_sig_user']; 
	if($from_share == NULL AND $from_embed == NULL AND $owner !== '0' AND $player !== '0') {
		$db->Raw("INSERT INTO `userdb_plays` (`owner`,`player`,`id`,`type`,`title`,`artist`) VALUES ('$owner','$player','$id','$type','$title','$artist')");
	}
}
$db->Raw("UPDATE `userdb_uploads` SET `count`=`count`+1 WHERE `id`='$id'"); // Updating individual song count.
?>